### ISSUE TITLE
Compiled with Problems

### ISSUE THREAD

**Issue by aegerev** [aegerev/NET-context#1]
ERROR in ./src/App.js 6:0-60
Module not found: Error: Can't resolve './components/SeriesContext' in 'C:\Development\The MERN Stack\bootcamp\portfolio-projects\NET-context\education-form\src'

ERROR in ./src/App.js 7:0-53
Module not found: Error: Can't resolve './components/SeriesList' in 'C:\Development\The MERN Stack\bootcamp\portfolio-projects\NET-context\education-form\src'

ERROR in ./src/components/AddSeries.js 6:0-51
Module not found: Error: Can't resolve './SeriesContext.js' in 'C:\Development\The MERN Stack\bootcamp\portfolio-projects\NET-context\education-form\src\components'

**Comment by aegerev** [comment]
The 'SeriesContext' errors are gone.

All that's left is this: 
ERROR in ./src/App.js 7:0-53
Module not found: Error: Can't resolve './components/SeriesList' in 'C:\Development\The MERN Stack\bootcamp\portfolio-projects\NET-context\education-form\src'

**Comment by aegerev** [comment]
All the Module errors are gone.

New problem:

addSeries is not a function
TypeError: addSeries is not a function
    at handleSubmit (http://localhost:3000/main.7a9358695611dbe39f89.hot-update.js:36:5)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:10047:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:10091:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:10148:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:10162:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:14305:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:14331:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:14342:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:14351:7)
    at http://localhost:3000/static/js/bundle.js:14511:16

**Comment by aegerev** [comment]
FAILED APP
